const storefront=(()=>{
  const labels={banner:'Banner',collection:'Coleção de produtos',image:'Imagem com texto',video:'Vídeo',text:'Texto',benefits:'Diferenciais da loja'};
  const defaultBenefits=[
    {icon:'truck',title:'Entrega com cuidado',body:'Consulte sua região'},
    {icon:'wallet',title:'Compra do seu jeito',body:'Combine o pagamento com a loja'},
    {icon:'shield',title:'Atendimento de verdade',body:'Nossa equipe cuida de você'},
    {icon:'store',title:'Sua loja de confiança',body:'Visite nossa loja física'}
  ];
  let selected='home-hero',previewSize='desktop';
  const home=()=>db.storefront;
  const section=()=>home().sections.find(s=>s.id===selected);
  const photo=(value)=>{const url=String(value||'').trim();return /^data:image\/(?:png|jpeg|webp);base64,[a-z0-9+/=]+$/i.test(url)||/^https?:\/\//i.test(url)?url:''};
  const shopLink=(value)=>{const url=String(value||'').trim();return /^\/loja(?:\/|$)/.test(url)||/^https:\/\//i.test(url)?url:'/loja/catalogo'};
  const cta=(s,preview)=>!s.buttonLabel?'':preview?`<span class="btn dark">${esc(s.buttonLabel)}</span>`:`<a class="btn dark" href="${esc(shopLink(s.buttonLink))}" ${/^https:\/\//i.test(s.buttonLink||'')?'target="_blank" rel="noopener"':''}>${esc(s.buttonLabel)}</a>`;
  const newId=()=>`sec-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,5)}`;
  function init(model){
    if(model.storefront?.sections?.length)return false;
    model.storefront={announcement:{enabled:true,text:'Uma casa cheia de possibilidades.',highlight:'Preços de outlet, todos os dias.'},sections:[
      {id:'home-hero',type:'banner',enabled:true,eyebrow:`Bem-vindo à ${model.settings.name}`,title:model.settings.hero,subtitle:model.settings.subtitle,image:seedProducts[0].image,imageAlt:'Sofá em uma sala de estar',buttonLabel:'Encontrar meu próximo móvel',buttonLink:'/loja/catalogo',align:'left'},
      {id:'home-benefits',type:'benefits',enabled:true,items:structuredClone(defaultBenefits)},
      {id:'home-products',type:'collection',enabled:true,eyebrow:'Escolhas para sua casa',title:'Seu novo favorito está aqui.',category:'Todos',limit:8}
    ]};
    return true;
  }
  function announcement(){const a=home().announcement;return a.enabled?`<div class="store-promo">${esc(a.text)} ${a.highlight?`<b>${esc(a.highlight)}</b>`:''}</div>`:''}
  function announcementControls(){const a=home().announcement;return `<section class="builder-card"><div class="builder-card-head"><div><span class="eyebrow">CABEÇALHO</span><h2>Faixa de aviso</h2></div><label class="builder-switch"><input type="checkbox" ${a.enabled?'checked':''} onchange="storefront.changeAnnouncement('enabled',this.checked)"><span>${a.enabled?'Visível':'Oculta'}</span></label></div><div class="builder-fields"><label class="field">Mensagem<input maxlength="110" value="${esc(a.text)}" oninput="storefront.changeAnnouncement('text',this.value)"></label><label class="field">Trecho em destaque<input maxlength="90" value="${esc(a.highlight)}" oninput="storefront.changeAnnouncement('highlight',this.value)"></label></div></section>`}
  function videoEmbed(raw){
    let url;try{url=new URL(String(raw||'').trim())}catch{return ''}
    if(!['https:','http:'].includes(url.protocol))return '';
    const host=url.hostname.toLowerCase().replace(/^www\./,'');let id='';
    if(host==='youtube.com'||host==='m.youtube.com'||host==='youtube-nocookie.com')id=url.searchParams.get('v')||url.pathname.match(/^\/(?:embed|shorts)\/([\w-]{11})/)?.[1]||'';
    if(host==='youtu.be')id=url.pathname.slice(1).split('/')[0];
    if(/^[\w-]{11}$/.test(id))return `<iframe src="https://www.youtube-nocookie.com/embed/${id}" title="Vídeo da loja" loading="lazy" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>`;
    if(host==='vimeo.com'||host==='player.vimeo.com'){const videoId=url.pathname.match(/(?:video\/)?(\d+)/)?.[1];if(videoId)return `<iframe src="https://player.vimeo.com/video/${videoId}" title="Vídeo da loja" loading="lazy" allow="fullscreen; picture-in-picture" allowfullscreen></iframe>`}
    if(/\.mp4(?:$|\?)/i.test(url.href))return `<video controls playsinline preload="metadata" src="${esc(url.href)}"></video>`;
    return '';
  }
  function renderSection(s,preview=false){
    if(!s.enabled)return '';
    if(s.type==='banner')return `<section class="store-hero storefront-banner ${s.align==='right'?'align-right':''}">${photo(s.image)?`<img class="hero-image" src="${esc(photo(s.image))}" alt="${esc(s.imageAlt||s.title||'Banner da loja')}" loading="lazy">`:''}<div class="hero-content">${s.eyebrow?`<span class="eyebrow">${esc(s.eyebrow)}</span>`:''}<h1>${esc(s.title||'Banner')}</h1>${s.subtitle?`<p>${esc(s.subtitle)}</p>`:''}${cta(s,preview)}</div></section>`;
    if(s.type==='benefits')return `<div class="store-benefits">${(s.items||[]).map(item=>`<div class="benefit">${icon(item.icon||'check')}<div><strong>${esc(item.title||'')}</strong><small>${esc(item.body||'')}</small></div></div>`).join('')}</div>`;
    if(s.type==='collection'){const category=s.category||'Todos';const products=db.products.filter(p=>p.active&&(category==='Todos'||p.category===category)).slice(0,Math.max(1,Math.min(24,Number(s.limit)||8)));return `<section class="storefront-collection"><div class="catalog-head"><div>${s.eyebrow?`<span class="eyebrow">${esc(s.eyebrow)}</span>`:''}<h2>${esc(s.title||category)}</h2></div>${preview?'<span class="text-link">Ver todos</span>':`<a class="text-link" href="/loja/catalogo" onclick="catalogCategory=decodeURIComponent('${encodeURIComponent(category).replace(/'/g,'%27')}')">Ver todos</a>`}</div><div class="catalog">${products.map(p=>preview?`<article class="shop-product"><div class="product-photo"><img src="${esc(p.image)}" alt="${esc(p.name)}" loading="lazy"></div><h3>${esc(p.name)}</h3>${priceMarkup(p)}</article>`:shopProduct(p)).join('')}</div>${products.length?'':`<p class="subtle">Nenhum produto ativo nesta coleção.</p>`}</section>`}
    if(s.type==='image')return `<section class="storefront-image ${s.layout==='image-right'?'image-right':''}"><div class="storefront-image-photo">${photo(s.image)?`<img src="${esc(photo(s.image))}" alt="${esc(s.imageAlt||s.title||'Imagem da loja')}" loading="lazy">`:'<span>Imagem ainda não adicionada</span>'}</div><div class="storefront-image-copy"><span class="eyebrow">${esc(s.eyebrow||'FORTE OUTLET')}</span><h2>${esc(s.title||'Sua casa merece esse cuidado.')}</h2><p>${esc(s.body||'')}</p>${cta(s,preview)}</div></section>`;
    if(s.type==='video')return `<section class="storefront-video"><div class="catalog-head"><div><span class="eyebrow">${esc(s.eyebrow||'INSPIRE-SE')}</span><h2>${esc(s.title||'Veja de perto')}</h2>${s.body?`<p>${esc(s.body)}</p>`:''}</div></div><div class="storefront-video-frame">${videoEmbed(s.url)||'<span>Adicione o link do vídeo para exibi-lo aqui.</span>'}</div></section>`;
    if(s.type==='text')return `<section class="storefront-text"><span class="eyebrow">${esc(s.eyebrow||'')}</span><h2>${esc(s.title||'Uma mensagem da loja')}</h2><p>${esc(s.body||'')}</p>${cta(s,preview)}</section>`;
    return '';
  }
  function storeHome(preview=false){const visible=home().sections.map(s=>renderSection(s,preview)).filter(Boolean);return `<div class="store-content storefront-home">${visible.map(html=>`<div class="home-section">${html}</div>`).join('')||'<div class="empty">A página inicial não tem seções visíveis.</div>'}</div>`}
  function preview(){return `<div class="preview-store ${previewSize==='mobile'?'preview-mobile':''}">${announcement()}<div class="preview-header"><img src="assets/logo.webp" alt="Grupo Outlet"><span>${icon('search')} Buscar móveis</span>${icon('cart')}</div>${storeHome(true)}</div>`}
  function sectionRow(s,i){return `<div class="builder-section-row ${selected===s.id?'active':''} ${s.enabled?'':'is-hidden'}"><button class="builder-section-select" onclick="storefront.select('${s.id}')"><span class="builder-section-icon">${icon(({banner:'image',image:'image',video:'eye',collection:'layers',text:'page',benefits:'shield'})[s.type])}</span><span><strong>${esc(s.title||labels[s.type])}</strong><small>${labels[s.type]}${s.enabled?'':' · Oculta'}</small></span></button><div class="builder-section-actions"><button title="Subir" aria-label="Subir ${esc(labels[s.type])}" onclick="storefront.move('${s.id}',-1)" ${i===0?'disabled':''}>↑</button><button title="Descer" aria-label="Descer ${esc(labels[s.type])}" onclick="storefront.move('${s.id}',1)" ${i===home().sections.length-1?'disabled':''}>↓</button></div></div>`}
  const input=(label,key,value,type='text',extra='')=>`<label class="field">${label}<input name="${key}" type="${type}" value="${esc(value||'')}" ${extra} oninput="storefront.change('${key}',this.value)"></label>`;
  const textarea=(label,key,value)=>`<label class="field">${label}<textarea name="${key}" oninput="storefront.change('${key}',this.value)">${esc(value||'')}</textarea></label>`;
  const choose=(label,key,value,options)=>`<label class="field">${label}<select name="${key}" onchange="storefront.change('${key}',this.value)">${options.map(([v,text])=>`<option value="${esc(v)}" ${value===v?'selected':''}>${esc(text)}</option>`).join('')}</select></label>`;
  const imageControls=(s,key='image')=>`${input('URL da imagem',key,s[key],'url','placeholder="https://..."')}<label class="field">Ou envie uma imagem<input type="file" accept="image/png,image/jpeg,image/webp" onchange="storefront.uploadImage(this,'${key}')"><small>JPG, PNG ou WebP · até 2 MB</small></label>${s[key]?`<div class="builder-image-preview"><img src="${esc(photo(s[key]))}" alt="Prévia da imagem"><button class="btn small" onclick="storefront.change('${key}','');storefront.render()">Remover imagem</button></div>`:''}`;
  function controls(s){
    if(s.type==='banner')return `${input('Texto pequeno acima do título','eyebrow',s.eyebrow)}${input('Título','title',s.title)}${textarea('Descrição','subtitle',s.subtitle)}${imageControls(s)}${input('Descrição da imagem','imageAlt',s.imageAlt)}${choose('Alinhamento do texto','align',s.align,[['left','À esquerda'],['right','À direita']])}${input('Texto do botão','buttonLabel',s.buttonLabel)}${input('Link do botão','buttonLink',s.buttonLink,'text','placeholder="/loja/catalogo"')}`;
    if(s.type==='collection')return `${input('Texto pequeno acima do título','eyebrow',s.eyebrow)}${input('Título','title',s.title)}${choose('Coleção','category',s.category,[['Todos','Todos os produtos'],...db.collections.map(c=>[c,c])])}${input('Número de produtos','limit',s.limit,'number','min="1" max="24"')}<button class="btn small" onclick="collectionModal()">Criar coleção</button>`;
    if(s.type==='image')return `${input('Texto pequeno acima do título','eyebrow',s.eyebrow)}${input('Título','title',s.title)}${textarea('Texto','body',s.body)}${imageControls(s)}${input('Descrição da imagem','imageAlt',s.imageAlt)}${choose('Posição da imagem','layout',s.layout,[['image-left','À esquerda'],['image-right','À direita']])}${input('Texto do botão','buttonLabel',s.buttonLabel)}${input('Link do botão','buttonLink',s.buttonLink,'text','placeholder="/loja/catalogo"')}`;
    if(s.type==='video')return `${input('Texto pequeno acima do título','eyebrow',s.eyebrow)}${input('Título','title',s.title)}${textarea('Texto','body',s.body)}${input('Link do vídeo','url',s.url,'url','placeholder="YouTube, Vimeo ou .mp4"')}<p class="builder-hint">Cole um link público do YouTube, Vimeo ou de um arquivo MP4. O vídeo não reproduz sozinho.</p>`;
    if(s.type==='text')return `${input('Texto pequeno acima do título','eyebrow',s.eyebrow)}${input('Título','title',s.title)}${textarea('Texto','body',s.body)}${input('Texto do botão','buttonLabel',s.buttonLabel)}${input('Link do botão','buttonLink',s.buttonLink)}`;
    if(s.type==='benefits')return (s.items||[]).map((item,i)=>`<div class="builder-benefit-fields"><h3>Diferencial ${i+1}</h3>${input('Título',`items.${i}.title`,item.title)}${input('Texto',`items.${i}.body`,item.body)}${choose('Ícone',`items.${i}.icon`,item.icon,[['truck','Entrega'],['wallet','Pagamento'],['shield','Confiança'],['store','Loja'],['check','Confirmação']])}</div>`).join('');
    return '';
  }
  function editorPage(){const s=section()||home().sections[0];selected=s.id;return heading('Loja online','Monte a página inicial e veja cada alteração na prévia.',button('Abrir loja','onclick="go(\'/loja\')"','','external'))+`<div class="storefront-builder"><div class="builder-column">${announcementControls()}<section class="builder-card"><div class="builder-card-head"><div><span class="eyebrow">PÁGINA INICIAL</span><h2>Seções da home</h2></div><span class="builder-count">${home().sections.length}</span></div><div class="builder-section-list">${home().sections.map(sectionRow).join('')}</div><button class="builder-add" onclick="storefront.addModal()">${icon('plus')} Adicionar seção</button><p class="builder-hint">Use as setas para mudar a ordem. Seções ocultas não aparecem na loja.</p></section><section class="builder-card"><div class="builder-card-head"><div><span class="eyebrow">EDITAR SEÇÃO</span><h2>${esc(labels[s.type])}</h2></div><label class="builder-switch"><input type="checkbox" ${s.enabled?'checked':''} onchange="storefront.toggle('${s.id}',this.checked)"><span>${s.enabled?'Visível':'Oculta'}</span></label></div><div class="builder-fields">${controls(s)}</div><div class="builder-card-foot"><button class="btn small" onclick="storefront.duplicate('${s.id}')">${icon('plus')} Duplicar</button><button class="btn small danger" onclick="storefront.removeModal('${s.id}')">${icon('trash')} Excluir</button></div></section></div><section class="builder-preview-panel"><div class="builder-preview-head"><div><strong>Prévia da página inicial</strong><small>As mudanças são salvas neste navegador</small></div><div class="builder-view-switch"><button class="${previewSize==='desktop'?'active':''}" onclick="storefront.setPreview('desktop')">Desktop</button><button class="${previewSize==='mobile'?'active':''}" onclick="storefront.setPreview('mobile')">Celular</button></div></div><div id="editor-preview">${preview()}</div></section></div>`}
  function render(){if(routePath().startsWith('/app/store-editor'))window.render()}
  function refresh(){const node=document.querySelector('#editor-preview');if(node)node.innerHTML=preview();const title=document.querySelector('.builder-section-row.active strong');if(title){const s=section();title.textContent=s.title||labels[s.type]}}
  function select(id){if(!home().sections.some(s=>s.id===id))return;selected=id;render()}
  function change(key,value){const s=section();if(!s)return;if(key.startsWith('items.')){const [,index,field]=key.split('.');if(!s.items?.[Number(index)]||!['title','body','icon'].includes(field))return;s.items[Number(index)][field]=value}else if(['eyebrow','title','subtitle','body','image','imageAlt','url','align','layout','buttonLabel','buttonLink','category','limit'].includes(key)){s[key]=key==='limit'?Math.max(1,Math.min(24,Number(value)||1)):value}else return;save();refresh()}
  function changeAnnouncement(key,value){if(!['enabled','text','highlight'].includes(key))return;home().announcement[key]=value;save();if(key==='enabled')render();else refresh()}
  function toggle(id,enabled){const s=home().sections.find(s=>s.id===id);if(!s)return;s.enabled=enabled;save();render()}
  function move(id,step){const list=home().sections,i=list.findIndex(s=>s.id===id),j=i+step;if(i<0||j<0||j>=list.length)return;[list[i],list[j]]=[list[j],list[i]];save();render()}
  function addModal(){modal('Adicionar seção',`<p>Escolha o tipo de conteúdo para a página inicial. A nova seção começa oculta até você terminar de editar.</p><div class="builder-add-grid">${Object.entries(labels).map(([type,label])=>`<button onclick="storefront.add('${type}')">${icon(({banner:'image',image:'image',video:'eye',collection:'layers',text:'page',benefits:'shield'})[type])}<strong>${label}</strong></button>`).join('')}</div>`)}
  function add(type){if(!labels[type])return;const base={id:newId(),type,enabled:false};const presets={banner:{eyebrow:'NOVIDADES',title:'Uma novidade para sua casa',subtitle:'',image:'',imageAlt:'',buttonLabel:'Ver produtos',buttonLink:'/loja/catalogo',align:'left'},collection:{eyebrow:'EXPLORE A LOJA',title:'Nossa seleção',category:'Todos',limit:4},image:{eyebrow:'FORTE OUTLET',title:'Sua casa merece esse cuidado.',body:'',image:'',imageAlt:'',layout:'image-left',buttonLabel:'',buttonLink:'/loja/catalogo'},video:{eyebrow:'INSPIRE-SE',title:'Veja de perto',body:'',url:''},text:{eyebrow:'NOSSA HISTÓRIA',title:'Sua casa merece o melhor.',body:'',buttonLabel:'',buttonLink:'/loja/catalogo'},benefits:{items:structuredClone(defaultBenefits)}};Object.assign(base,presets[type]);home().sections.push(base);selected=base.id;save();closeModal();render();toast('Seção adicionada. Edite o conteúdo e ative a visibilidade.')}
  function duplicate(id){const list=home().sections,i=list.findIndex(s=>s.id===id);if(i<0)return;const copy=structuredClone(list[i]);copy.id=newId();copy.title=copy.title?`${copy.title} (cópia)`:copy.title;copy.enabled=false;list.splice(i+1,0,copy);selected=copy.id;save();render();toast('Seção duplicada e oculta para edição.')}
  function removeModal(id){const s=home().sections.find(s=>s.id===id);if(!s)return;modal('Excluir seção',`<p>Excluir <strong>${esc(s.title||labels[s.type])}</strong> da página inicial?</p><div class="form-actions"><button class="btn" onclick="closeModal()">Manter seção</button><button class="btn danger" onclick="storefront.remove('${id}')">Excluir seção</button></div>`)}
  function remove(id){const list=home().sections,i=list.findIndex(s=>s.id===id);if(i<0)return;if(list.length===1){closeModal();toast('Oculte a última seção ou adicione outra antes de excluir.');return}list.splice(i,1);selected=list[Math.min(i,list.length-1)]?.id||'';save();closeModal();render();toast('Seção excluída.')}
  async function uploadImage(input,key){const s=section();if(!s||!input.files?.[0])return;try{const data=await imageData(input.files[0]),old=s[key];s[key]=data;if(!save()){s[key]=old;return}render();toast('Imagem adicionada à seção.')}catch(error){toast(error.message)}}
  function setPreview(size){previewSize=size==='mobile'?'mobile':'desktop';document.querySelector('.builder-preview-panel')?.classList.toggle('show-mobile',previewSize==='mobile');render()}
  return {init,announcement,storeHome,editorPage,change,changeAnnouncement,toggle,move,addModal,add,duplicate,removeModal,remove,select,uploadImage,setPreview,render};
})();
